import { Injectable } from '@angular/core';
import { Subject } from 'rxjs/Subject';

/**
 * A service to generate writing prompts
 *
 * @export
 * @class WritingPromptService
 */
@Injectable()
export class WritingPromptService {
  prompts: string[] = [];
  private promptSelectedSource = new Subject<string>();

  // Observable string streams
  promptSelected$ = this.promptSelectedSource.asObservable();

  constructor() {
    this._get_raw_prompts();
  }

  // Service message commands
  selectPrompt(prompt: string) {
    this.promptSelectedSource.next(prompt);
  }

  private _get_raw_prompts() {
    const prompts = [
      '##COUNT## ##KEYWORD## Ideas That Can Impress Your Friends',
      '##COUNT## ##KEYWORD## Issues And How To Solve Them',
      '##COUNT## ##KEYWORD## Mistakes You Should Never Make',
      '##COUNT## ##KEYWORD## Mistakes You\'re Making Without Even Realizing It',
      '##COUNT## ##KEYWORD## Secrets You Never Knew',
      '##COUNT## ##KEYWORD## That Had Gone Way Too Far',
      '##COUNT## ##KEYWORD## That Will Actually Make Your Life Better',
      '##COUNT## ##KEYWORD## Tips From ##KEYWORD## Experts',
      '##COUNT## ##KEYWORD## Tips You Need To Learn Now',
      '##COUNT## ##KEYWORD## Trends You Should Know Before Even Starting Your Business',
      '##COUNT## Actionable Tips on ##KEYWORD## And Twitter',
      '##COUNT## Advantages Of ##KEYWORD## And How You Can Make Full Use Of It',
      '##COUNT## Advices That You Must Lis##COUNT## Before Studying ##KEYWORD##',
      '##COUNT## Advices That You Must Lis##COUNT## To Before Learning ##KEYWORD##',
      '##COUNT## Alternatives To ##KEYWORD##',
      '##COUNT## Amazing ##KEYWORD## Hacks',
      '##COUNT## and a Half Very Simple Things You Can Do To Save ##KEYWORD##',
      '##COUNT## Apps You Didn\'t Know That Can Enhance Your ##KEYWORD##',
      '##COUNT## Awesome Lessons You Can Learn From Studying The ##KEYWORD## Industry',
      '##COUNT## Awesome Things You Can Learn From ##KEYWORD##',
      '##COUNT## Awesome Things You Can Learn From Studying ##KEYWORD##',
      '##COUNT## Awesome Tips About ##KEYWORD## From Unlikely Websites',
      '##COUNT## Basic Tools You Will Need To Learn ##KEYWORD##',
      '##COUNT## Beautiful Reasons We Can\'t Help But Fall In Love With ##KEYWORD##',
      '##COUNT## Benefits Of ##KEYWORD## That May Change Your Perspective',
      '##COUNT## Best Practices For ##KEYWORD##',
      '##COUNT## Best Things About ##KEYWORD##',
      '##COUNT## Best Tweets Of All Time About ##KEYWORD##',
      '##COUNT## Best Ways To Sell ##KEYWORD##',
      '##COUNT## Biggest ##KEYWORD## Mistakes You Can Easily Avoid',
      '##COUNT## Brilliant Ways To Advertise ##KEYWORD##',
      '##COUNT## Brilliant Ways To Teach Your Audience About ##KEYWORD##',
      '##COUNT## Brilliant Ways To Use ##KEYWORD##',
      '##COUNT## Clarifications On ##KEYWORD##',
      '##COUNT## Common Misconceptions About ##KEYWORD##',
      '##COUNT## Common Mistakes Everyone Makes In ##KEYWORD##',
      '##COUNT## Common Myths About ##KEYWORD##',
      '##COUNT## Common Myths About The ##KEYWORD## Industry',
      '##COUNT## Conventional Advertising Methods That Will Jeopardize ##KEYWORD##',
      '##COUNT## Crazy Trends In The ##KEYWORD## Industry',
      '##COUNT## Creative Ways You Can Improve Your ##KEYWORD##',
      '##COUNT## Critical Skills To Do ##KEYWORD## Loss Remarkably Well',
      '##COUNT## Days To A Better ##KEYWORD##',
      '##COUNT## Days To Improving The Way You ##KEYWORD##',
      '##COUNT## Difficult Things About ##KEYWORD##',
      '##COUNT## Disadvantages Of ##KEYWORD## And How You Can Workaround It',
      '##COUNT## DIY ##KEYWORD## Tips You May Have Missed',
      '##COUNT## Documentaries About ##KEYWORD## That Will Truly Change The Way You See ##KEYWORD##',
      '##COUNT## Doubts About ##KEYWORD## You Should Clarify',
      '##COUNT## Doubts You Should Clarify About ##KEYWORD##',
      '##COUNT## Easy Rules Of ##KEYWORD##',
      '##COUNT## Easy Ways To ##KEYWORD## Without Even Thinking About It',
      '##COUNT## Easy Ways To Facilitate ##KEYWORD##',
      '##COUNT## Easy Ways To Make ##KEYWORD## Faster',
      '##COUNT## Easy Ways You Can Turn ##KEYWORD## Into Success',
      '##COUNT## Effective Ways To Get More Out Of ##KEYWORD##',
      '##COUNT## Emerging ##KEYWORD## Trends To Watch In 2016',
      '##COUNT## Essential Strategies To ##KEYWORD##',
      '##COUNT## Explanation On Why ##KEYWORD## Is Important',
      '##COUNT## Facebook Pages To Follow About ##KEYWORD##',
      '##COUNT## Factors That Affect ##KEYWORD##',
      '##COUNT## Factors That Affect ##KEYWORD##\'s Longevity',
      '##COUNT## Facts About ##KEYWORD## That Will Blow Your Mind',
      '##COUNT## Facts About ##KEYWORD## That Will Make You Think Twice',
      '##COUNT## Facts Everyone Should Know About ##KEYWORD##',
      '##COUNT## Facts That Nobody Told You About ##KEYWORD##',
      '##COUNT## Facts You Never Knew About ##KEYWORD##',
      '##COUNT## Features Of ##KEYWORD## That Make Everyone Love It',
      '##COUNT## Fishy Things That Nobody Told You About ##KEYWORD## Industry',
      '##COUNT## Fundamental Rules You Can\'t Afford To Ignore When It Comes To ##KEYWORD##',
      '##COUNT## Funny ##KEYWORD## Quotes',
      '##COUNT## Gigantic Influences Of ##KEYWORD##',
      '##COUNT## Great ##KEYWORD## Ideas That You Can Share With Your Friends',
      '##COUNT## Great Lessons You Can Learn From ##KEYWORD##',
      '##COUNT## Great Tips To Earn More In The ##KEYWORD## Industry',
      '##COUNT## Great Tips To Earn More With ##KEYWORD##',
      '##COUNT## Guilt Free ##KEYWORD## Tips',
      '##COUNT## Habits Of Highly Effective ##KEYWORD##',
      '##COUNT## Hidden ##KEYWORD## Features That Will Make Your Life Easier',
      '##COUNT## Horrible Mistakes To Avoid When You Do ##KEYWORD##',
      '##COUNT## Ideas About ##KEYWORD## That Really Work',
      '##COUNT## Important Facts That You Should Know About ##KEYWORD##',
      '##COUNT## Important Facts That You Should Know About The ##KEYWORD## Industry',
      '##COUNT## Important Life Lessons ##KEYWORD## Taught Us',
      '##COUNT## Inconvenient Truth Why You Can\'t Master ##KEYWORD##',
      '##COUNT## Incredible ##KEYWORD## Examples',
      '##COUNT## Incredible ##KEYWORD## Transformations',
      '##COUNT## Incredibly Useful ##KEYWORD## Tips For Small Businesses',
      '##COUNT## Ingenious Ideas For You To Explore With ##KEYWORD##',
      '##COUNT## Ingenious Ways You Can Do With ##KEYWORD##',
      '##COUNT## Innovative Approaches To Improve Your ##KEYWORD##',
      '##COUNT## Inspirational Quotes About ##KEYWORD##',
      '##COUNT## Key Tactics The Pros Use For ##KEYWORD##',
      '##COUNT## Kinds Of ##KEYWORD##: Which One Will Make The Most Money',
      '##COUNT## Latest Developments In ##KEYWORD##',
      '##COUNT## Laws Of ##KEYWORD##',
      '##COUNT## Lessons About ##KEYWORD## You Need To Learn To Succeed',
      '##COUNT## Lessons I\'ve Learned From ##KEYWORD##',
      '##COUNT## Lessons That Will Teach You All You Need To Know About ##KEYWORD##',
      '##COUNT## Lessons You Can Learn From Bing About ##KEYWORD##',
      '##COUNT## Life-Saving Tips About ##KEYWORD##',
      '##COUNT## Little Tricks To Achieve The Best Results In ##KEYWORD##',
      '##COUNT## Mesmerizing Examples Of ##KEYWORD##',
      '##COUNT## Methods Of ##KEYWORD## Domination',
      '##COUNT## Mind Numbing Facts About ##KEYWORD##',
      '##COUNT## Mind-Blowing Reasons Why ##KEYWORD## Is Using This Technique For Exposure',
      '##COUNT## Mind-Blowing Reasons Why ##KEYWORD## Is Using This Technique For Exposure',
      '##COUNT## Mistakes In ##KEYWORD## That Make You Look Dumb',
      '##COUNT## Moments That Basically Sum Up Your ##KEYWORD## Experience',
      '##COUNT## Moments To Remember From ##KEYWORD##',
      '##COUNT## More Cool Tools For ##KEYWORD##',
      '##COUNT## More Reasons To Be Excited About ##KEYWORD##',
      '##COUNT## Most Common Problems With ##KEYWORD##',
      '##COUNT## Most Popular Ways To ##KEYWORD##',
      '##COUNT## Must Know Tips If You Want To Avoid Failure In ##KEYWORD##',
      '##COUNT## Myths About ##KEYWORD##',
      '##COUNT## New Age Ways To ##KEYWORD##',
      '##COUNT## New Thoughts About ##KEYWORD## That Will Turn Your World Upside Down',
      '##COUNT## No Cost Ways To Get More With ##KEYWORD##',
      '##COUNT## Of The Punniest ##KEYWORD## Puns You Can Find',
      '##COUNT## Outrageous Ideas For Your ##KEYWORD##',
      '##COUNT## Places That You Can Find ##KEYWORD##',
      '##COUNT## Places To Get Deals On ##KEYWORD##',
      '##COUNT## Powerful Tips To Help You ##KEYWORD## Better',
      '##COUNT## Practical Tactics to Turn ##KEYWORD## Into a Sales Machine',
      '##COUNT## Precious Tips To Help You Get Better At ##KEYWORD##',
      '##COUNT## Precious Tips To Help You Get Better In ##KEYWORD## Industry',
      '##COUNT## Preparations You Should Make Before Using ##KEYWORD##',
      '##COUNT## Problems Everyone Has With ##KEYWORD## – How To Solved Them',
      '##COUNT## Pros And Cons Of Being In ##KEYWORD## Industry',
      '##COUNT## Proven ##KEYWORD## Techniques',
      '##COUNT## Questions About ##KEYWORD## You Should Answer Truthfully',
      '##COUNT## Questions Answered About ##KEYWORD##',
      '##COUNT## Questions On ##KEYWORD##',
      '##COUNT## Questions To Ask At ##KEYWORD##',
      '##COUNT## Questions You Need To Ask About ##KEYWORD##',
      '##COUNT## Quick Tips For ##KEYWORD##',
      '##COUNT## Quick Tips Regarding ##KEYWORD##',
      '##COUNT## Quick Tips To Mastering ##KEYWORD##',
      '##COUNT## Reason Why You Should Consider Picking Up ##KEYWORD##',
      '##COUNT## Reasons ##KEYWORD## Is A Waste Of Time',
      '##COUNT## Reasons Owning ##KEYWORD## Will Change Your Life',
      '##COUNT## Reasons The Quality Of ##KEYWORD## Is So Much More Important Than Quantity',
      '##COUNT## Reasons Why ##KEYWORD## Is Common In USA',
      '##COUNT## Reasons Why Everyone Is Learning ##KEYWORD## These Days',
      '##COUNT## Reasons Why Facebook Is The Worst Option For ##KEYWORD##',
      '##COUNT## Reasons Why Having An Excellent ##KEYWORD## Is Not Enough',
      '##COUNT## Reasons Why Having An Excellent ##KEYWORD## Isn\'t Enough',
      '##COUNT## Reasons Why People Like ##KEYWORD##',
      '##COUNT## Reasons Why People Love ##KEYWORD##',
      '##COUNT## Reasons Why You Are A Rookie In ##KEYWORD##',
      '##COUNT## Reasons Why You Are Still An Amateur At ##KEYWORD##',
      '##COUNT## Reasons Why You Cannot Learn ##KEYWORD## Well',
      '##COUNT## Reasons Why You Should Invest In ##KEYWORD##',
      '##COUNT## Reasons Why You Shouldn\'t Learn ##KEYWORD## On Your Own',
      '##COUNT## Reasons Why You Shouldn\'t Rely On ##KEYWORD## Anymore',
      '##COUNT## Reasons Why You\'re Still A Rookie In ##KEYWORD##',
      '##COUNT## Reasons You Need To Stop Stressing About ##KEYWORD##',
      '##COUNT## Reasons You Should Fall In Love With ##KEYWORD##',
      '##COUNT## Reasons Your ##KEYWORD## Is Not What It Should Be',
      '##COUNT## Reliable Sources To Learn About ##KEYWORD##',
      '##COUNT## Reliable Sources To Learn About The ##KEYWORD## Industry',
      '##COUNT## Ridiculous Rules About ##KEYWORD##',
      '##COUNT## Romantic ##KEYWORD## Ideas',
      '##COUNT## Rules About ##KEYWORD## Meant To Be Broken',
      '##COUNT## Scary ##KEYWORD## Ideas',
      '##COUNT## Secret Things You Didn\'t Know About ##KEYWORD##',
      '##COUNT## Secrets About ##KEYWORD## That Has Never Been Revealed For The Past ##COUNT## Years',
      '##COUNT## Secrets About ##KEYWORD## That Nobody Will Tell You',
      '##COUNT## Secrets That Experts Of ##KEYWORD## Don\'t Want You To Know',
      '##COUNT## Secrets You Will Not Want To Know About ##KEYWORD##',
      '##COUNT## Secrets: How To Use ##KEYWORD## To Create A Successful Business/Product',
      '##COUNT## Sexy Ways To Improve Your ##KEYWORD##',
      '##COUNT## Shitty Things ##KEYWORD## Have Done',
      '##COUNT## Shocking Facts About ##KEYWORD##',
      '##COUNT## Short Stories You Didn\'t Know About ##KEYWORD##',
      '##COUNT## Shortcuts For ##KEYWORD## That Gets Your Result In Record Time',
      '##COUNT## Signs You\'re In Love With ##KEYWORD##',
      '##COUNT## Simple (But Important) Things To Remember About ##KEYWORD##',
      '##COUNT## Simple Steps To An Effective ##KEYWORD## Strategy',
      '##COUNT## Simple Tips For Using ##KEYWORD## To Get Ahead Your Competition',
      '##COUNT## Small But Important Things To Observe In ##KEYWORD##',
      '##COUNT## Small Changes That Will Have A Huge Impact On Your ##KEYWORD##',
      '##COUNT## Solid Evidences Learning ##KEYWORD## Is Good For Your Career Advancement',
      '##COUNT## Solid Evidences Why ##KEYWORD## Is Bad For Your Career Development',
      '##COUNT## Solid Reasons To Avoid ##KEYWORD##',
      '##COUNT## Step Checklist for ##KEYWORD##',
      '##COUNT## Stereotypes About ##KEYWORD## That Aren\'t Always True',
      '##COUNT## Strange Facts About ##KEYWORD##',
      '##COUNT## Struggles Only People In ##KEYWORD## Industry Will Understand',
      '##COUNT## Stupid Questions You Should Have Asked Before Starting ##KEYWORD##',
      '##COUNT## Stylish Ideas For Your ##KEYWORD##',
      '##COUNT## Super Useful Tips To Improve ##KEYWORD##',
      '##COUNT## Surefire Ways ##KEYWORD## Will Drive Your Business Into The Ground',
      '##COUNT## Taboos About ##KEYWORD## You Should Never Share On Twitter',
      '##COUNT## Teachings That Can Empower Your Business In ##KEYWORD##',
      '##COUNT## Thing I Like About ##KEYWORD##, But ###COUNT## Is My Favorite',
      '##COUNT## Things About ##KEYWORD## That You Want... Badly',
      '##COUNT## Things About ##KEYWORD## You Have To Experience It Yourself',
      '##COUNT## Things Everyone Knows About ##KEYWORD## That You Don\'t',
      '##COUNT## Things I Wish I Knew About ##KEYWORD##',
      '##COUNT## Things I Would Do If I\'d Start Again ##KEYWORD##',
      '##COUNT## Things Nobody Told You About ##KEYWORD##',
      '##COUNT## Things People Hate About ##KEYWORD##',
      '##COUNT## Things That Happen When You Are In ##KEYWORD##',
      '##COUNT## Things That Matter When You Are Learning ##KEYWORD##',
      '##COUNT## Things That You Never Expect On ##KEYWORD##',
      '##COUNT## Things To Avoid In ##KEYWORD##',
      '##COUNT## Things To Do Immediately About ##KEYWORD##',
      '##COUNT## Things To Know About ##KEYWORD##',
      '##COUNT## Things Twitter Wants Yout To Forget About ##KEYWORD##',
      '##COUNT## Things You Didn\'t Know About ##KEYWORD##',
      '##COUNT## Things You Have In Common With ##KEYWORD##',
      '##COUNT## Things You Most Likely Didn\'t Know About ##KEYWORD##',
      '##COUNT## Things You Must Know About ##KEYWORD##',
      '##COUNT## Things You Must Know Before Trying ##KEYWORD##',
      '##COUNT## Things You Need To Know About ##KEYWORD## Today',
      '##COUNT## Things You Probably Didn\'t Know About ##KEYWORD##',
      '##COUNT## Things You Should Do In ##KEYWORD##',
      '##COUNT## Things You Should Know About ##KEYWORD##',
      '##COUNT## Things You Should Know Before Getting Into The ##KEYWORD## Industry',
      '##COUNT## Things Your Boss Needs To Know About ##KEYWORD##',
      '##COUNT## Things Your Boss Needs To Know About The ##KEYWORD## Industry',
      '##COUNT## Things Your Competitors Know About ##KEYWORD##',
      '##COUNT## Things Your Competitors Know About The ##KEYWORD## Industry',
      '##COUNT## Tips About ##KEYWORD## You Can\'t Afford To Miss',
      '##COUNT## Tips For ##KEYWORD## Success',
      '##COUNT## Tips From A ##KEYWORD## Pro',
      '##COUNT## Tips That Will Change The Way You ##KEYWORD##',
      '##COUNT## Tips That Will Make You Influential In ##KEYWORD##',
      '##COUNT## Tips To Avoid Failure In ##KEYWORD##',
      '##COUNT## Tips To Start Building A ##KEYWORD## You Always Wanted',
      '##COUNT## Top Hidden Risks In The ##KEYWORD## Industry',
      '##COUNT## Top Reasons Why You Face Obstacles In Learning ##KEYWORD##',
      '##COUNT## Top Risks Of ##KEYWORD##',
      '##COUNT## Top Risks Of Owning ##KEYWORD##',
      '##COUNT## Trendy Ways To Improve On ##KEYWORD##',
      '##COUNT## Tricks About ##KEYWORD## You Wish You Knew Before',
      '##COUNT## Tricks You Must Know When Using ##KEYWORD##',
      '##COUNT## Ugly Truth About ##KEYWORD##',
      '##COUNT## Unbelievable Facts About ##KEYWORD##',
      '##COUNT## Unconventional Knowledge About ##KEYWORD## That You Can\'t Learn From Books',
      '##COUNT## Undeniable Facts About ##KEYWORD##',
      '##COUNT## Unexpected Ways ##KEYWORD## Can Make Your Life Better',
      '##COUNT## Unforgivable Sins Of ##KEYWORD##',
      '##COUNT## Unheard Ways To Achieve Greater ##KEYWORD##',
      '##COUNT## Useful Tips From Experienced ##KEYWORD## Practitioners',
      '##COUNT## Useful Tips From Experienced ##KEYWORD## Veteran',
      '##COUNT## Useful Tips From Experts In ##KEYWORD##',
      '##COUNT## Various Ways To Do ##KEYWORD##',
      '##COUNT## Very Common Misconceptions About The ##KEYWORD## Industry',
      '##COUNT## Very Simple Things You Can Do To Save Time With ##KEYWORD##',
      '##COUNT## Warning Signs Of Your ##KEYWORD## Demise',
      '##COUNT## Ways ##KEYWORD## Can Improve Your Business',
      '##COUNT## Ways ##KEYWORD## Can Make You Invincible',
      '##COUNT## Ways ##KEYWORD## Will Help You Get More Business',
      '##COUNT## Ways Create Better ##KEYWORD## With The Help Of Your Dog',
      '##COUNT## Ways Of ##KEYWORD## That Can Drive You Bankrupt - Fast',
      '##COUNT## Ways To ##KEYWORD## Without Breaking Your Bank',
      '##COUNT## Ways To Achieve Your Goals In ##KEYWORD## Faster',
      '##COUNT## Ways To Avoid ##KEYWORD## Burnout',
      '##COUNT## Ways To Get Through To Your ##KEYWORD##',
      '##COUNT## Ways To Have A More Appealing ##KEYWORD##',
      '##COUNT## Ways To Have Fun Learning ##KEYWORD##',
      '##COUNT## Ways To Immediately Start Selling ##KEYWORD##',
      '##COUNT## Ways To Improve ##KEYWORD##',
      '##COUNT## Ways To Improve Your ##KEYWORD## Skills',
      '##COUNT## Ways To Introduce ##KEYWORD##',
      '##COUNT## Ways To Keep Your ##KEYWORD## Growing Without Burning The Midnight Oil',
      '##COUNT## Ways To Learn ##KEYWORD## Effectively',
      '##COUNT## Ways to Make Your ##KEYWORD## Easier',
      '##COUNT## Ways To Master ##KEYWORD## Without Breaking A Sweat',
      '##COUNT## Ways To Reinvent Your ##KEYWORD##',
      '##COUNT## Ways To Simplify ##KEYWORD##',
      '##COUNT## Ways To Tell You\'re Suffering From An Obession With ##KEYWORD##',
      '##COUNT## Ways To Use ##KEYWORD## To Your Advantage',
      '##COUNT## Ways Twitter Destroyed My ##KEYWORD## Without Me Noticing',
      '##COUNT## Ways You Can ##KEYWORD## Without Investing Too Much Of Your Time',
      '##COUNT## Ways You Can Get More ##KEYWORD## While Spending Less',
      '##COUNT## Ways You Can Grow Your Creativity Using ##KEYWORD##',
      '##COUNT## Ways You Can Reinvent ##KEYWORD## Without Looking Like An Amateur',
      '##COUNT## Ways You Can Use ##KEYWORD## To Become Irresistible To Customers',
      '##COUNT## Wonderful ##KEYWORD##. Number ##COUNT## is Absolutely Stunning',
      '##KEYWORD## ##COUNT## Minutes A Day To Grow Your Business',
      '##KEYWORD## - Are You Prepared For A Good Thing',
      '##KEYWORD## - Choosing The Right Strategy',
      '##KEYWORD## - How To Be More Productive',
      '##KEYWORD## - It Never Ends, Unless...',
      '##KEYWORD## - Not For Everyone',
      '##KEYWORD## - Pay Attentions To These ##COUNT## Signals',
      '##KEYWORD## - Relax, It\'s Play Time',
      '##KEYWORD## - So Simple Even Your Kids Can Do It',
      '##KEYWORD## - The Six Figure Challenge',
      '##KEYWORD## - What Can You Learn From Your Critics',
      '##KEYWORD## - What Do Those Stats Really Mean',
      '##KEYWORD## - What To Do When Rejected',
      '##KEYWORD## 2.0 - The Next Step',
      '##KEYWORD## Abuse - How Not To Do It',
      '##KEYWORD## Adventures',
      '##KEYWORD## An Incredibly Easy Method That Works For All',
      '##KEYWORD## And Love - How They Are The Same',
      '##KEYWORD## And Love Have ##COUNT## Things In Common',
      '##KEYWORD## And Other Products',
      '##KEYWORD## And The Art Of Time Management',
      '##KEYWORD## And The Chuck Norris Effect',
      '##KEYWORD## Blueprint - Rinse And Repeat',
      '##KEYWORD## Changes: ##COUNT## Actionable Tips',
      '##KEYWORD## Cheet Sheet',
      '##KEYWORD## Conferences',
      '##KEYWORD## Consulting – What The Heck Is That',
      '##KEYWORD## Creates Experts',
      '##KEYWORD## Data We Can All Learn From',
      '##KEYWORD## Doesn\'t Have To Be Hard. Read These ##COUNT## Tricks Go Get A Head Start',
      '##KEYWORD## Ethics',
      '##KEYWORD## Ethics and Etiquette',
      '##KEYWORD## Experiment We Can All Learn From',
      '##KEYWORD## Experiment: Good or Bad',
      '##KEYWORD## Expert Interview',
      '##KEYWORD## Explained',
      '##KEYWORD## Explained 101',
      '##KEYWORD## Fears – Death',
      '##KEYWORD## For Business: The Rules Are Made To Be Broken',
      '##KEYWORD## For Dollars',
      '##KEYWORD## For Dollars Seminar',
      '##KEYWORD## For Fun',
      '##KEYWORD## For Money',
      '##KEYWORD## For Profit',
      '##KEYWORD## For Sale – How Much Is Yours Worth',
      '##KEYWORD## Gets A Redesign',
      '##KEYWORD## Guides And Reports',
      '##KEYWORD## Has The Answer To Everything',
      '##KEYWORD## Helps You Achieve Your Dreams',
      '##KEYWORD## Hopes and Dreams',
      '##KEYWORD## in ##YEAR## – Predictions',
      '##KEYWORD## Iphone Apps',
      '##KEYWORD## Is A Great Way To Increase Your Profit',
      '##KEYWORD## Is Bound To Make An Impact In Your Business',
      '##KEYWORD## Is Crucial To Your Business. Learn Why',
      '##KEYWORD## Is Essential For Your Success. Read This To Find Out Why',
      '##KEYWORD## Is Not Rocket Science! Learn Them Now',
      '##KEYWORD## Is So Famous, But Why',
      '##KEYWORD## Is Your Worst Enemy. ##COUNT## Ways To Defeat It',
      '##KEYWORD## It! Lessons From The Oscars',
      '##KEYWORD## Like A Pro With The Help Of These ##COUNT## Tips',
      '##KEYWORD## Made Simple - Even Your Kids Can Do It',
      '##KEYWORD## Mindset. Genius Idea',
      '##KEYWORD## Money Experiment',
      '##KEYWORD## Not Resulting In Financial Prosperity',
      '##KEYWORD## Once, ##KEYWORD## Twice: ##COUNT## Reasons Why You Shouldn\'t ##KEYWORD## The Third Time',
      '##KEYWORD## Opportunities For Everyone',
      '##KEYWORD## Predictions For ##YEAR##',
      '##KEYWORD## Promotion 101',
      '##KEYWORD## Question: Does Size Matter',
      '##KEYWORD## Report: Statistics and Facts',
      '##KEYWORD## Resources: google.com (or any specific website name)',
      '##KEYWORD## Review',
      '##KEYWORD## Reviewed: What Can One Learn From Other\'s Mistakes',
      '##KEYWORD## Services - How To Do It Right',
      '##KEYWORD## Shortcuts - The Easy Way',
      '##KEYWORD## Smackdown',
      '##KEYWORD## Stats: These Numbers Are Real',
      '##KEYWORD## Strategies For Beginners',
      '##KEYWORD## Strategies Revealed',
      '##KEYWORD## The Right Way',
      '##KEYWORD## Will Be A Thing Of The Past And Here\'s Why',
      '##KEYWORD## Will Make You Tons Of Cash. Here\'s How',
      '##KEYWORD## Without Driving Yourself Crazy',
      '##KEYWORD## Works Only Under These Conditions',
      '##KEYWORD## Your Way To Success',
      '##KEYWORD##! ##COUNT## Tricks The Competition Knows, But You Don\'t',
      '##KEYWORD##: A List of ##COUNT## Things That\'ll Put You In a Good Mood',
      '##KEYWORD##: An Incredibly Easy Method That Works For All',
      '##KEYWORD##: Back To Basics',
      '##KEYWORD##: Do You Really Need It? This Will Help You Decide',
      '##KEYWORD##: Is Not That Difficult As You Think',
      '##KEYWORD##: Keep It Simple (And Stupid)',
      '##KEYWORD##: Launching Your Own Affiliate Program',
      '##KEYWORD##: Quality vs Quantity',
      '##KEYWORD##: The Easy Way',
      '##KEYWORD##: The Google Strategy',
      '##KEYWORD##: The Samurai Way',
      '##KEYWORD##: This Is What Professionals Do',
      '##KEYWORD##: What A Mistake',
      '##KEYWORD##? It\'s Easy If You Do It Smart',
      '##KEYWORD## Like An Expert. Follow These ##COUNT## Steps To Get There',
      '##YEAR## Is The Year Of ##KEYWORD##',
      '##COUNT## Ideas For ##KEYWORD##',
      '##COUNT## Lessons Learned From the Pros On ##KEYWORD##',
      '59% Of The Market Is Interested In ##KEYWORD##',
      'A Beautifully Refreshing Perspective On ##KEYWORD##',
      'A Good ##KEYWORD## Is...',
      'A Guide To ##KEYWORD## At Any Age',
      'A New Model For ##KEYWORD##',
      'A Short Course In ##KEYWORD##',
      'A Simple Plan For ##KEYWORD##',
      'A Surprising Tool To Help You ##KEYWORD##',
      'Add These ##COUNT## Mangets To Your ##KEYWORD##',
      'Advanced ##KEYWORD##',
      'All You Need To Know About ##KEYWORD##',
      'Amateurs ##KEYWORD## But Overlook A Few Simple Things',
      'An Analysis Of ##COUNT## ##KEYWORD## Strategies... Here\'s What We Learned',
      'Answered: Your Most Burning Questions About ##KEYWORD##',
      'Anyone Who Has A Problem With ##KEYWORD## Needs To Know One Thing',
      'Apply Any Of These ##COUNT## Secret Techniques To Improve ##KEYWORD##',
      'Apply These ##COUNT## Secret Techniques To Improve ##KEYWORD##',
      'Are You ##KEYWORD## The Best You Can? ##COUNT## Signs Of Failure',
      'Are You ##KEYWORD## The Right Way? These ##COUNT## Tips Will Help You Answer',
      'Are You Actually Doing Enough ##KEYWORD##',
      'Are You Embarrassed By Your ##KEYWORD## Skills? Here\'s What To Do',
      'Are You Good At ##KEYWORD##? Here\'s A Quick Quiz To Find Out',
      'Are You Making These ##KEYWORD## Mistakes',
      'Are You Ready For ##KEYWORD##? Take This Quick Quiz To Find Out',
      'Are You Ready For This Year\'s ##KEYWORD## Industry',
      'Are You Struggling With ##KEYWORD##? Let\'s Chat',
      'Arguments For Getting Rid Of ##KEYWORD##',
      'Arguments of Getting Rid Of ##KEYWORD##',
      'At Last, The Secret To ##KEYWORD## Is Revealed',
      'Attention-grabbing Ways To ##KEYWORD##',
      'Avoid The Top ##COUNT## ##KEYWORD## Mistakes',
      'Avoid The Top ##COUNT## Mistakes Made By Beginning ##KEYWORD##',
      'Back To Basics. The ##COUNT## Fundamentals That Everyone Always Forget About ##KEYWORD##',
      'Be A Pioneer In The ##KEYWORD## Industry. Here\'s What You\'ll Need',
      'Being A Star In Your Industry Is A Matter Of ##KEYWORD##',
      'Believe In Your ##KEYWORD## Skills But Never Stop Improving',
      'Believing Any Of These ##COUNT## Myths About ##KEYWORD## Keeps You From Growing',
      'Best ##COUNT## Tips For ##KEYWORD##',
      'Best ##KEYWORD## Android/iPhone Apps',
      'Best Make ##KEYWORD## You Will Read This Year',
      'Beware The ##KEYWORD## Scam',
      'Beware: ##COUNT## ##KEYWORD## Mistakes',
      'Boost Your ##KEYWORD## With These Tips',
      'Building Relationships With ##KEYWORD##',
      'Can You Pass The ##KEYWORD## Test',
      'Can You Really Find ##KEYWORD## on the Web/Market',
      'Can You Spot The A ##KEYWORD## Pro',
      'Cash For ##KEYWORD##',
      'Cats, Dogs and ##KEYWORD##',
      'Clear And Unbiased Facts About ##KEYWORD## Without All the Hype',
      'Congratulations! Your ##KEYWORD## Is/Are About To Stop Being Relevant',
      'Cool Little ##KEYWORD## Tool',
      'Could This Report Be The Definitive Answer To Your ##KEYWORD##',
      'Cracking The ##KEYWORD## Code',
      'Crazy ##KEYWORD##: Lessons From The Pros',
      'Death, ##KEYWORD## And Taxes',
      'Did You Start ##KEYWORD## For Passion or Money',
      'Do ##KEYWORD## Better Than Barack Obama',
      'Does ##KEYWORD## Sometimes Make You Feel Stupid',
      'Does Your ##KEYWORD## Goals Match Your Practices',
      'Don\'t ##KEYWORD## Unless You Use These ##COUNT## Tools',
      'Don\'t Be Fooled By ##KEYWORD##',
      'Don\'t Fall For This ##KEYWORD## Scam',
      'Don\'t Get Too Excited. You May Not Be Done With ##KEYWORD##',
      'Don\'t Just Sit There! Start ##KEYWORD##',
      'Don\'t Waste Time! ##COUNT## Facts To Start ##KEYWORD##',
      'Double Your Profit With These ##COUNT## Tips on ##KEYWORD##',
      'Dreaming Of ##KEYWORD##',
      'Earning a Six Figure Income From ##KEYWORD##',
      'Easy Steps To ##KEYWORD## Of Your Dreams',
      'Eliminate Your Fear And Pick Up ##KEYWORD## Today',
      'Eliminate Your Fears And Doubts About ##KEYWORD##',
      'Enhance Your ##KEYWORD## Skills During Your Lunch Break',
      'Essential ##KEYWORD## Smartphone Apps',
      'Ever Heard About Extreme ##KEYWORD##? Well About That',
      'Everyone Is Flocking To Work In The ##KEYWORD## Industry. But Why',
      'Everything You Need To Know About ##KEYWORD##',
      'Everything You Wanted to Know About ##KEYWORD## and Were Afraid To Ask',
      'Everything You Wanted to Know About ##KEYWORD## and Were Too Embarrassed to Ask',
      'Extreme ##KEYWORD##',
      'Fall In Love With ##KEYWORD##',
      'Fascinating ##KEYWORD## Tactics That Can Help Your Business Grow',
      'Fast-Track Your ##KEYWORD##',
      'Favorite ##KEYWORD## Resources For ##YEAR##',
      'Fear? Not If You Use ##KEYWORD## The Right Way',
      'Fears of a Professional ##KEYWORD##',
      'Find A Quick Way To ##KEYWORD##',
      'Find Out How I Cured My ##KEYWORD## In ##COUNT## Days',
      'Find Out Now, What Should You Do For Fast ##KEYWORD##',
      'Finding Customers With ##KEYWORD##',
      'Five Rookie ##KEYWORD## Mistakes You Can Fix Today',
      'Free ##KEYWORD## Coaching Servies',
      'Free Advice On ##KEYWORD##',
      'Free Advice On Profitable ##KEYWORD##',
      'Fully Utilize ##KEYWORD## To Enhance Your Business',
      'Genius! How To Figure Out If You Should Really Do ##KEYWORD##',
      'Get Better ##KEYWORD## Results By Following ##COUNT## Simple Steps',
      'Get Rid of ##KEYWORD## For Good',
      'Get Rid of ##KEYWORD## Once and For All',
      'Get The Most Out of ##KEYWORD## and Facebook',
      'Getting The Best Software To Power Up Your ##KEYWORD##',
      'Got Stuck? Try These Tips To Streamline Your ##KEYWORD##',
      'Guaranteed No Stress ##KEYWORD##',
      'Have You Heard? ##KEYWORD## Is Your Best Bet To Grow',
      'Heard Of The ##KEYWORD## Effect? Here It Is',
      'Heard Of The Great ##KEYWORD## BS Theory? Here Is A Great Example',
      'Here Are ##COUNT## ##KEYWORD## Tactics Everyone Believes In. Which One Do You Prefer',
      'Here Are ##COUNT## Ways To Better ##KEYWORD##',
      'Here Is A Method That Is Helping ##KEYWORD##',
      'Here Is A Quick Cure For ##KEYWORD##',
      'Here Is What You Should Do For Your ##KEYWORD##',
      'Here\'s A Quick Way To Solve A Problem with ##KEYWORD##',
      'Here\'s An Inside Look At The Latest ##KEYWORD##Video That Brought Joy On YouTube',
      'Here\'s the science behind A Perfect ##KEYWORD##',
      'Here\'s What Industry Insiders Say About ##KEYWORD##',
      'Here\'s What No One Tells You About ##KEYWORD##',
      'Here\'s What People Are Saying About ##KEYWORD##',
      'Here\'s Why ##COUNT## Million Customers In the US Are ##KEYWORD##',
      'Here, Copy This Idea on ##KEYWORD##',
      'Ho To Do ##KEYWORD## Without Leaving Your Office/House',
      'How ##COUNT## Stories Will Change The Way You Approach ##KEYWORD##',
      'How ##KEYWORD## Became A Globally Well-Known Brand',
      'How ##KEYWORD## Can Ease Your Pain',
      'How ##KEYWORD## Can Help You Improve Your Health',
      'How ##KEYWORD## Can Increase Your Profit',
      'How ##KEYWORD## Is Going To Change Your Business Strategies',
      'How ##KEYWORD## Made Me A Better Salesperson',
      'How ##KEYWORD## Makes Me Feel Good',
      'How Did We Get There? The History Of ##KEYWORD## Told Through Tweets',
      'How Do You Choose The Best ##KEYWORD##',
      'How Google Is Changing How We Approach ##KEYWORD##',
      'How Google Uses ##KEYWORD## To Grow Bigger',
      'How I Got Started With ##KEYWORD##',
      'How I Improved My ##KEYWORD## In One Day',
      'How I Improved My ##KEYWORD## In One Easy Lesson',
      'How Important is ##KEYWORD##. ##COUNT## Expert Quotes',
      'How Learning ##KEYWORD## Could Save Your Money And Time',
      'How Much Do You Charge For ##KEYWORD##',
      'How To ##KEYWORD## Better In Less Time',
      'How To Be In The Top ##COUNT## With ##KEYWORD##',
      'How To Be Successful In The ##KEYWORD## Industry',
      'How To Become Better With ##KEYWORD## In ##COUNT## Minutes',
      'How To Buy A ##KEYWORD## On A Tight Budget',
      'How to Create Your ##KEYWORD## Strategy [Blueprint]',
      'How To Deal With A Very Bad ##KEYWORD##',
      'How To Earn $398/Day Using ##KEYWORD##',
      'How To Find The Right ##KEYWORD## For Your Specific Product/Service',
      'How To Find The Time To ##KEYWORD## On Twitter',
      'How To Get A Fabulous ##KEYWORD## On A Tight Budget',
      'How To Get Discovered With ##KEYWORD##',
      'How To Get People To Like ##KEYWORD##',
      'How to Grow Your ##KEYWORD## Income',
      'How To Guide: ##KEYWORD## Essentials For Beginners',
      'How To Handle Every ##KEYWORD## Challenge With Ease Using These Tips',
      'How To Have A Fantastic ##KEYWORD## With Minimal Spending',
      'How To Improve At ##KEYWORD## In ##COUNT## Minutes',
      'How To Learn ##KEYWORD##',
      'How To Learn ##KEYWORD## Without Losing Your Mind',
      'How To Learn About ##KEYWORD## In Only ##COUNT## Days',
      'How To Leave ##KEYWORD## Without Being Noticed',
      'How To Lose Money With ##KEYWORD##',
      'How To Make Money From The ##KEYWORD## Phenomenon',
      'How To Make More ##KEYWORD## By Doing Less',
      'How To Make Your ##KEYWORD## Look Amazing In ##COUNT## Days',
      'How To Make Your ##KEYWORD## Look Like A Million Bucks',
      'How To Make Your Product Stand Out With ##KEYWORD##',
      'How To Master ##KEYWORD## In Only ##COUNT## Days',
      'How To Master ##KEYWORD## With The Best ##KEYWORD## Tips In Pictures',
      'How To Own ##KEYWORD## For Free',
      'How To Quit ##KEYWORD## In ##COUNT## Days',
      'How To Save Money with ##KEYWORD##',
      'How To Sell ##KEYWORD##',
      'How To Spread The Word About Your ##KEYWORD##',
      'How To Start ##KEYWORD## With Less Than $100',
      'How To Start A Business With ##KEYWORD##',
      'How To Take The Headache Out Of ##KEYWORD##',
      'How To Teach ##KEYWORD## Better Than Anyone Else',
      'How To Teach ##KEYWORD## Like A Pro',
      'How To Turn ##KEYWORD## Into Success',
      'How To Turn Your ##KEYWORD## From Zero To Hero',
      'How To Use ##KEYWORD## To Desire',
      'How To Win Buyers And Influence Sales with ##KEYWORD##',
      'How To Win Clients And Influence Markets with ##KEYWORD##',
      'How To Win Friends And Influence People with ##KEYWORD##',
      'How We Improved Our ##KEYWORD## In One Week/Month/Day',
      'How Will ##KEYWORD## Be In The Future',
      'How You Can Do ##KEYWORD## Almost Instantly',
      'How You Can Do ##KEYWORD## In ##COUNT## Hours Or Less For Free',
      'How You Can Own ##KEYWORD## With Lower Cost',
      'How You Know You\'re Doing ##KEYWORD## The Right Way',
      'I Answered The Toughest##KEYWORD## Question So You Don\'t Have To (But You Might Want To)',
      'I Don\'t Want To Spend This Much Time On ##KEYWORD##. How About You',
      'I Finally Tried ##KEYWORD## For A Week And This Is What Happened',
      'I Will Tell You The Truth About ##KEYWORD## In The Next ##COUNT## Seconds',
      'If ##KEYWORD## Is So Terrible, Why Don\'t Statistics Show It',
      'If You Do Not Do ##KEYWORD## Now, You Will Hate Yourself Later',
      'If You Want To Be A Winner, Change Your ##KEYWORD## Philosophy Now',
      'If You Want To Be Successful In ##KEYWORD##, Here Are ##COUNT## Invaluable Things To Know',
      'Improve Your ##KEYWORD## Skills',
      'Improve/Increase Your ##KEYWORD## In ##COUNT## Days',
      'In ##COUNT## Minutes, I\'ll Give You The Truth About ##KEYWORD##',
      'In the Age of Information, Specializing in ##KEYWORD##',
      'Interesting Facts I Bet You Never Knew About ##KEYWORD##',
      'Introducing A Revolutionary Method To Master ##KEYWORD##',
      'Introducing The Simple Way To ##KEYWORD##',
      'Is ##KEYWORD## Any Good? ##COUNT## Ways You Can Be Certain',
      'Is ##KEYWORD## Making Me Rich',
      'Is ##KEYWORD## Still Relevant',
      'Is ##KEYWORD## The Most Trending Thing Now',
      'Is ##KEYWORD## Worth [$] To You',
      'Is It Time to Talk More About ##KEYWORD##',
      'Is It Time To Talk More ABout ##KEYWORD##',
      'Is This ##KEYWORD## Thing Really That Hard',
      'It\'s All About ##KEYWORD##',
      'It\'s The Side Of Extreme ##KEYWORD## Rarely Seen, But That\'s Why Is Needed',
      'It\'s The Side of Extreme ##KEYWORD## Rarely Seen, But That\'s Why It\'s Needed',
      'Learn All About ##KEYWORD## From This Politician',
      'Learn Anything New From ##KEYWORD## Lately? We Asked, You Answered',
      'Learn Exactly How I Improved ##KEYWORD## In ##COUNT## Days',
      'Learn Exactly How We Made ##KEYWORD## Last Month',
      'Learn From These Mistakes Before You Learn ##KEYWORD##',
      'Learn How To ##KEYWORD## Persuasively In ##COUNT## Easy Steps',
      'Learn How To Make More Money With ##KEYWORD##',
      'Learn How To Start ##KEYWORD##',
      'Learn The Truth About ##KEYWORD## In The Next ##COUNT## Seconds',
      'Learn The Truth About ##KEYWORD## Industry In The Next ##COUNT## Seconds',
      'Learn To Do ##KEYWORD## Like A Professional',
      'Learning ##KEYWORD## Can Be Addictive. Here\'s How You Can Get Yourself Hooked',
      'Learning ##KEYWORD## Can Be Disastrous If You Neglect These ##COUNT## Simple Rules',
      'Learning ##KEYWORD## Is Not Difficult At All! You Just Need A Great Teacher',
      'Less = More With ##KEYWORD##',
      'Lies And Damn Lies About ##KEYWORD##',
      'Listen To Your Customers. They Will Tell You All About ##KEYWORD##',
      'Little Known Ways to ##KEYWORD##',
      'Little Known Ways To Rid Yourself Of ##KEYWORD##',
      'Look Ma, You Can Actually Build a Bussiness With ##KEYWORD##',
      'Make The Most Out Of ##KEYWORD##',
      'Make Your ##KEYWORD##A Reality',
      'Make Your Parents Proud By Learning ##KEYWORD##',
      'Marketing And ##KEYWORD##',
      'Marriage And ##KEYWORD## Have More In Common Than You Think',
      'Master ##KEYWORD## In Just A Few Hours',
      'Master ##KEYWORD## in ##COUNT## Minutes A Day',
      'Master The Art Of ##KEYWORD## With These ##COUNT## Tips',
      'Master The Skills Of ##KEYWORD## And Be Successful',
      'Mastering The Way Of ##KEYWORD## Is Not An Accident - It\'s An Art',
      'Mind Blowing Method On ##KEYWORD##',
      'More on ##KEYWORD##',
      'More on Making a Living Off of ##KEYWORD##',
      'Most Effective Ways To Overcome ##KEYWORD##\'s Problem',
      'Must Have List Of ##KEYWORD## Networks',
      'Must Have Resources For ##KEYWORD##',
      'My Biggest ##KEYWORD## Lesson',
      'Need More Inspiration With ##KEYWORD##? Read this',
      'Need More Time? Read These Tips To Eliminate ##KEYWORD##',
      'Never Changing ##KEYWORD## Will Eventually Destroy You',
      'Never Lose Your ##KEYWORD## Again',
      'Never Mess With ##KEYWORD## And Here\'s The Reasons Why',
      'Never Suffer From ##KEYWORD## Again',
      'Never Underestimate The Influence Of ##KEYWORD##',
      'No More Mistakes With ##KEYWORD##',
      'Nothing To See Here. Just A Bunch Of Us Agreeing a ##COUNT## Basic ##KEYWORD## Rules',
      'Now Is The Time For You To Know The Truth About ##KEYWORD##',
      'Now You Can Buy An App That is Really Made For ##KEYWORD##',
      'Now You Can Have The ##KEYWORD## Of Your Dreams – Cheaper/Faster Than You Ever Imagined',
      'Now You Can Have Your ##KEYWORD## Done Safely',
      'Old School ##KEYWORD##',
      'OMG! The Best ##KEYWORD## Ever',
      'One Surprisingly Effective Way To ##KEYWORD##',
      'One Tip To Dramatically Improve Your ##KEYWORD##',
      'Open Mike on ##KEYWORD##',
      'Open The Gates For ##KEYWORD## By Using These Simple Tips',
      'Picture Your ##KEYWORD## On Top. Read This And Make It So',
      'Poll: How Much Do You Earn From ##KEYWORD##',
      'Prepare To Laugh: ##KEYWORD## Is Not Harmless As you Might Think. Take A Look At These Great Examples',
      'Proof That ##KEYWORD## Is Exactly What You Are Looking For',
      'Proof That ##KEYWORD## Really Works',
      'Questions For/About ##KEYWORD##',
      'Quick and Easy Fix For Your ##KEYWORD##',
      'Quiz: How Much Do You Know about ##KEYWORD##',
      'Random ##KEYWORD## Tip',
      'Read This Controversial Article And Find Out More About ##KEYWORD##',
      'Read This To Change How You ##KEYWORD##',
      'Reasons Why ##KEYWORD## Is Getting More Popular In The Past Decade',
      'Remarkable Website - ##KEYWORD## Will Help You Get There',
      'Revolutionize Your ##KEYWORD## With These Easy-peasy Tips',
      'Ridiculously Simple Ways To Improve Your ##KEYWORD##',
      'Rules Not To Follow About ##KEYWORD##',
      'Savvy|Smart|Sexy People Do ##KEYWORD## :)',
      'Se7en Worst ##KEYWORD## Techniques',
      'Secrets About ##KEYWORD##',
      'Secrets To ##KEYWORD## – Even In This Down Economy',
      'Secrets To Getting ##KEYWORD## To Complete Tasks Quickly And Efficiently',
      'Seductive ##KEYWORD##',
      'Sexy ##KEYWORD##',
      'Short Story: The Truth About ##KEYWORD##',
      'Should Fixing ##KEYWORD## Take ##COUNT## Steps',
      'Sick And Tired Of Doing ##KEYWORD## The Old Way? Read This',
      'Signs You Made A Great Impact On ##KEYWORD##',
      'Simple Guidance For You In ##KEYWORD##',
      'Simple Steps To A ##COUNT## Minute ##KEYWORD##',
      'Sins Of ##KEYWORD##',
      'Skills That You Can Learn From ##KEYWORD##',
      'Skills That You Can Learn In The ##KEYWORD## Industry',
      'Solid Reasons To Avoid ##KEYWORD##',
      'Some Facts About ##KEYWORD## That Will Make You Feel Better',
      'Some People Excel At ##KEYWORD## And Some Don\'t - Which One Are You',
      'Stop Wasting Time And Start ##KEYWORD##',
      'Strange Facts About ##KEYWORD##',
      'Street Talk: ##KEYWORD##',
      'Succeed With ##KEYWORD## In ##COUNT## Hours',
      'Successful Stories You Didn’t Know About ##KEYWORD##',
      'Super Easy Simple Ways The Pros Use To Promote ##KEYWORD##',
      'Super Useful Tips To Improve ##KEYWORD##',
      'SuperEasy Ways To Learn Everything About ##KEYWORD##',
      'Take ##COUNT## Minutes to Get Started With ##KEYWORD##',
      'Take Advantage Of ##KEYWORD## - Read These ##COUNT## Tips',
      'Take Home Lessons On ##KEYWORD##',
      'Take The Stress Out Of ##KEYWORD##',
      'Take This ##KEYWORD## Test And You\'ll See Your Struggles. Literally',
      'The ###COUNT## ##KEYWORD## Mistake, Plus ##COUNT## More Lessons',
      'The ##COUNT## Common Stereotypes When It Comes To ##KEYWORD##',
      'The ##COUNT## Key Elements In ##KEYWORD##',
      'The ##COUNT## Really Obvious Ways To ##KEYWORD## Better That You Ever Did',
      'The ##COUNT## Reasons Tourists Love ##KEYWORD##',
      'The ##COUNT## Secrets About ##KEYWORD## Only A Handful Of People Know',
      'The ##COUNT## Secrets That You Shouldn\'t Know About ##KEYWORD##',
      'The ##COUNT## Secrets To Effective ##KEYWORD##',
      'The ##COUNT## Secrets You Will Never Know About ##KEYWORD##',
      'The ##COUNT## Steps Needed For Putting ##KEYWORD## Into Action',
      'The ##KEYWORD## Mystery Revealed',
      'The ##KEYWORD## That Wins Customers',
      'The A - Z Guide Of ##KEYWORD##',
      'The Advanced Guide To ##KEYWORD##',
      'The Advantages Of Being In ##KEYWORD## Industry',
      'The Advantages Of Different Types Of ##KEYWORD##',
      'The Anatomy Of ##KEYWORD##',
      'The Anthony Robins Guide To ##KEYWORD##',
      'The Best ##COUNT## Examples Of ##KEYWORD##',
      'The Best Advice You Could Ever Get About ##KEYWORD##',
      'The best explanation of ##KEYWORD## I have ever heard',
      'The Best Way To ##KEYWORD##',
      'The Biggest Contribution Of ##KEYWORD## To Humanity',
      'The Biggest Disadvantage Of Using ##KEYWORD##',
      'The Biggest Lie In ##KEYWORD##',
      'The Biggest Problem in ##KEYWORD## Comes Down To This Word That Starts With W',
      'The Billionaire Guide On ##KEYWORD## That Helps You Get Rich',
      'The Billionaire Guide On ##KEYWORD## That Will Get You Rich',
      'The Business Of ##KEYWORD##',
      'The Complete Guide To Understanding ##KEYWORD##',
      'The Complete Process of ##KEYWORD##',
      'The Consequences Of Failing To ##KEYWORD## When Launching Your Business',
      'The Critical Difference Between ##KEYWORD## and Google',
      'The Death Of ##KEYWORD## And How To Avoid It',
      'The Death Of ##KEYWORD##',
      'The Definitive Guide To ##KEYWORD##',
      'The Difference Between ##KEYWORD## And Other Similar Items',
      'The Etiquette of ##KEYWORD##',
      'The Evolution Of ##KEYWORD##',
      'The Future Of ##KEYWORD##',
      'The Hidden Agenda Of ##KEYWORD## Industry',
      'The Hidden Agenda Of ##KEYWORD##',
      'The Hidden Mystery Behind ##KEYWORD##',
      'The History of ##KEYWORD##',
      'The Hollistic Aproach To ##KEYWORD##',
      'The Impact Of ##KEYWORD## On Your Customers/Followers',
      'The Latest ##KEYWORD## Has Finally Been Revealed',
      'The Latest Development About ##KEYWORD## That You Have To Know',
      'The Latest Trend In ##KEYWORD##',
      'The Lazy Man\'s Guide To ##KEYWORD##',
      'The Lazy Way To ##KEYWORD##',
      'The Millionaire Guide On ##KEYWORD## To Help You Get Rich',
      'The Miracle Of ##KEYWORD##',
      'The Modern Rules Of ##KEYWORD##',
      'The Most/Least Effective Ideas In ##KEYWORD##',
      'The Most Common ##KEYWORD## Debate Isn\'t As Simple As You May Think',
      'The Most Common Mistakes People Make With ##KEYWORD##',
      'The Most Important Elements Of ##KEYWORD##',
      'The Most Unconventional Ways to Learn ##KEYWORD##',
      'The Next ##COUNT## Things To Immediately Do About ##KEYWORD##',
      'The No. 1 ##KEYWORD## Mistake You\'re Making and ##COUNT## Ways To Fix It',
      'The Number One Reason You Should Do ##KEYWORD##',
      'The Philosophy Of ##KEYWORD##',
      'The Power Of ##KEYWORD##',
      'The Problem With The New ##KEYWORD##',
      'The Pros And Cons Of ##KEYWORD##',
      'The Quickest & Easiest Way To ##KEYWORD##',
      'The Rank Of ##KEYWORD## In Consumer\'s Market',
      'The Real Reason We Need To Stop Trying Too Hard In ##KEYWORD##',
      'The Real Story Behind ##KEYWORD##',
      'The Reason Why Everyone Love ##KEYWORD##',
      'The Reasons Why We Love ##KEYWORD##',
      'The Reasons Why We Love The ##KEYWORD## Industry',
      'The Secret Code To ##KEYWORD##. Yours, For Free... Really',
      'The Secret of ##KEYWORD##',
      'The Secret Of ##KEYWORD##',
      'The Secret of Successful ##KEYWORD##',
      'The Secrets To ##KEYWORD##',
      'The Secrets To Finding World Class Tools For Your ##KEYWORD## Quickly',
      'The Shocking Revelation of ##KEYWORD##',
      'The Single Most Important Thing You Need To Know About ##KEYWORD##',
      'The Story Of ##KEYWORD## Has Just Gone Viral',
      'The Ten Commandments Of ##KEYWORD##',
      'The Top ##COUNT## Pros And Cons Of ##KEYWORD##',
      'The Trending Stuff About ##KEYWORD##',
      'The Truth About ##KEYWORD## In ##COUNT## Minutes',
      'The Truth About ##KEYWORD## Is About To Be Revealed',
      'The Truth Is You Are Not The Only Person Concerned About ##KEYWORD##',
      'The Ugly Truth About ##KEYWORD##',
      'The Ultimate Deal On ##KEYWORD##',
      'The Ultimate Guide To ##KEYWORD##',
      'The Ultimate Revelation Of ##KEYWORD##',
      'The Ultimate Revelation On The ##KEYWORD## Industry',
      'The Ultimate Secret Of ##KEYWORD##',
      'The Ultimate Strategy To ##KEYWORD##',
      'The Untapped Gold Mine Of ##KEYWORD## That Virtually No One Knows About',
      'The Untold Secret To ##KEYWORD## In Less Than Ten Minutes',
      'The Untold Secret To Mastering ##KEYWORD## In Just ##COUNT## Days',
      'The Wildest Thing About ##KEYWORD## Is Not Even How Disgusting It Is',
      'The World\'s Best ##KEYWORD## You Can Actually Buy',
      'The World\'s Most Unusual ##KEYWORD##',
      'The World\'s Worst Advice On ##KEYWORD##',
      'The Worst Advices We\'ve Heard For ##KEYWORD##',
      'There\'s A Right Way To Talk About ##KEYWORD## And There\'s Another Way',
      'There\'s No Point Doing ##KEYWORD## If You\'re Not Doing It Right',
      'There’s Big Money In ##KEYWORD##',
      'These ##COUNT## Hacks Will Make You ##KEYWORD## Look Like A Pro',
      'These ##COUNT## Inspirational Quotes Will Help You Survive in The ##KEYWORD## World',
      'These ##COUNT## Simple ##KEYWORD## Tricks Will Pump Up Your Sales Almost Instantly',
      'These Facts Just Might Get You To Change Your ##KEYWORD## Strategy',
      'These Local Practices In ##KEYWORD## Are So Bizarre That They Will Make Your Jaw Drop',
      'Things That Make You Love And Hate ##KEYWORD##',
      'Think Of A ##KEYWORD##. Now Draw A ##KEYWORD##. I Bet You\'ll Make The Same Mistake As Most People Do',
      'Think You\'re An Expert In ##KEYWORD##? Take This Quiz Now To Find Out',
      'Thinking About ##KEYWORD##? ##COUNT## Reasons Why It\'s Time To Stop',
      'This Is How ##KEYWORD## Will Look Like In ##COUNT## Years Time',
      'This Is Why ##KEYWORD## Is So Famous',
      'This Is Why This Year Will Be The Year Of ##KEYWORD##',
      'This Is Why You Face Obstacles In Learning ##KEYWORD##',
      'This Story Behind ##KEYWORD## Will Haunt You Forever',
      'This Study Will Perfect Your ##KEYWORD##: Read Or Miss Out',
      'This Test Will Show You Wheter You\'re An Expert in ##KEYWORD## Without Knowing It. Here\'s How It Works',
      'This Year Will Be The Year of ##KEYWORD##',
      'Three Quick Ways To Learn ##KEYWORD##',
      'Time Is Running Out! Think About These ##COUNT## Ways To Change Your ##KEYWORD##',
      'Time-tested Ways To ##KEYWORD##',
      'To Click Or Not To Click: ##KEYWORD## And Blogging',
      'To People That Want To Start ##KEYWORD## But Are Affraid To Get Started',
      'Top ##COUNT## ##KEYWORD## Accounts To Follow On Twitter',
      'Top ##COUNT## ##KEYWORD## Related Trends To Keep In View',
      'Top ##COUNT## Books About ##KEYWORD##',
      'Top ##COUNT## Common Prejudices About ##KEYWORD##',
      'Top ##COUNT## Key Tactics The Pros Use For ##KEYWORD##',
      'Top ##COUNT## Quotes On ##KEYWORD##',
      'Top ##COUNT## Sites You Can Learn ##KEYWORD## For Free',
      'Top ##COUNT## Tips To Grow Your ##KEYWORD##',
      'Top ##COUNT## Tips With ##KEYWORD##',
      'Top ##COUNT## Trends In ##KEYWORD## To Watch',
      'Top ##COUNT## Ways To Buy A Used ##KEYWORD##',
      'Top ##COUNT## Websites To Look For ##KEYWORD##',
      'Top ##COUNT## YouTube Clips About ##KEYWORD##',
      'Triple Your Results At ##KEYWORD## In Half The Time',
      'Turn Your ##KEYWORD## Into A High Performing Machine',
      'Understand ##KEYWORD## Before You Regret',
      'Understand The Background Of ##KEYWORD## Now',
      'Understanding ##KEYWORD##',
      'Understanding The Background Of ##KEYWORD## Industry',
      'Understanding The Background Of ##KEYWORD##',
      'Use ##KEYWORD## To Make Someone Fall In Love With You',
      'Using ##COUNT## ##KEYWORD## Strategies Like The Pros',
      'Want A Thriving Business? Focus On ##KEYWORD##',
      'Want More Money? Start ##KEYWORD##',
      'Want More Out Of Your Life? ##KEYWORD##, ##KEYWORD##, ##KEYWORD##',
      'Want To Step Up Your ##KEYWORD##? You Need To Read This First',
      'Watch Them Completely Ignoring ##KEYWORD## And Learn The Lesson',
      'We Wanted To Draw Attention To ##KEYWORD##.So Did You',
      'Welcome to a New Look Of ##KEYWORD##',
      'What ##KEYWORD## Industry Really Is',
      'What $3##COUNT## Buys You In ##KEYWORD##',
      'What Alberto Savoia Can Teach You About ##KEYWORD##',
      'What Are The ##COUNT## Main Benefits Of ##KEYWORD##',
      'What Can Instagramm Teach You About ##KEYWORD##',
      'What Can You Do About ##KEYWORD## Right Now',
      'What Can You Do To Save Your ##KEYWORD## From Destruction By Social Media',
      'What Causes The Emerging Trend Of ##KEYWORD## Industry In Asia',
      'What Could ##KEYWORD## Do To Make You Switch',
      'What Do You Want ##KEYWORD## To Become',
      'What Every ##KEYWORD## Need To Know About Facebook',
      'What Everyone Must Know About ##KEYWORD##',
      'What Everyone Ought To Know About ##KEYWORD##',
      'What I Wish Everyone Knew About ##KEYWORD##',
      'What Is ##KEYWORD## and How Does It Work',
      'What It\'s Like Dating ##KEYWORD##',
      'What Make ##KEYWORD## Don\'t Want You To Know',
      'What Will ##KEYWORD## Be Like In The Next ##COUNT## Years',
      'What Will The ##KEYWORD## Industry Be Like In The Next ##COUNT## Years',
      'What You Can Learn From Bill Gates About ##KEYWORD##',
      'What You Can Learn From Politician About The ##KEYWORD## Industry',
      'What You Didn\'t Realize About ##KEYWORD## Is Powerful - But Extremely Simple',
      'What You Know About ##KEYWORD## And What You Don\'t Know About ##KEYWORD##',
      'What You Should Have Asked Your Teachers About ##KEYWORD##',
      'What Your Customers Really Think About Your ##KEYWORD##',
      'What\'s New About ##KEYWORD##',
      'What\'s Right About ##KEYWORD##',
      'What\'s So Trendy About ##KEYWORD## That Everyone Went Crazy Over It',
      'What\'s Wrong With ##KEYWORD##',
      'When ##KEYWORD## Businesses Grow Too Quickly',
      'When ##KEYWORD## Competition is Good',
      'When ##KEYWORD## Means More Than Money',
      'When Is The Right Time To Start ##KEYWORD##',
      'When Professionals Run Into Problems With ##KEYWORD##, This Is What They Do',
      'When You Ask People About ##KEYWORD## This Is What They Answer',
      'Where Can You Find Free ##KEYWORD## Resources',
      'Where Is The Best ##KEYWORD##',
      'Where To Start With ##KEYWORD##',
      'Where Will ##KEYWORD## Be ##COUNT## Months From Now',
      'Who Else Wants To Be Successful With ##KEYWORD##',
      'Who Else Wants To Enjoy ##KEYWORD##',
      'Who Else Wants To Know The Mystery Behind ##KEYWORD##',
      'Who is Your ##KEYWORD## Customer',
      'Why ##KEYWORD## Doesn\'t Work…For Everyone',
      'Why ##KEYWORD## Had Been So Popular Till Now',
      'Why ##KEYWORD## Is A Tactic Not A Strategy',
      'Why ##KEYWORD## Is No Friend To Small Business',
      'Why ##KEYWORD## Is The Only Skill You Really Need',
      'Why ##KEYWORD## Succeeds',
      'Why Are Children Getting Addicted To ##KEYWORD## Nowadays',
      'Why Are Children So Obsessed With ##KEYWORD##',
      'Why Everything You Know About ##KEYWORD## Is A Lie',
      'Why Experts Say The ##KEYWORD## Industry Had Gone Way Too Far',
      'Why I Hate ##KEYWORD##',
      'Why Ignoring ##KEYWORD## Will Cost You Time and Sales',
      'Why Is ##KEYWORD## Considered Underrated',
      'Why Is ##KEYWORD## So Famous',
      'Why Is ##KEYWORD## The Most Trending Thing Now',
      'Why Is Everyone Talking About ##KEYWORD##',
      'Why It Is Not The Best Time To Pick Up ##KEYWORD## Now',
      'Why It\'s Easier To Fail With ##KEYWORD## Than You Might Think',
      'Why Learning ##KEYWORD## Can Actually Improve Your Health Condition',
      'Why Most ##KEYWORD## Fail',
      'Why Most People Will Never Be Great At ##KEYWORD##',
      'Why My ##KEYWORD## Is Better Than Yours',
      'Why Some People Almost Always Make/Save Money With ##KEYWORD##',
      'Why You Must Experience ##KEYWORD## At Least Once In Your Lifetime',
      'Why You Never See ##KEYWORD## That Actually Works',
      'Why You Really Need ##KEYWORD##',
      'Why You Should Not Go To ##KEYWORD##',
      'Why You Shouldn\'t Venture Into The ##KEYWORD## Industry Now',
      'Will ##KEYWORD## Ever Die',
      'Winning Philosophy For The ##KEYWORD## Industry',
      'Winning Tactics For ##KEYWORD##',
      'Wondering How To Make Your ##KEYWORD## Rock? Read This',
      'Working In The ##KEYWORD## Industry Can Be Disastrous If You Don\'t Follow These ##COUNT## Rules',
      'World Class Tools Make ##KEYWORD## Push Button Easy',
      'You Can Thank Us Later - ##COUNT## Reasons To Stop Thinking About ##KEYWORD##',
      'You Don\'t Have To Be A Big Corporation To Start ##KEYWORD##',
      'You Should Experience ##KEYWORD## At Least Once In Your Lifetime And Here\'s Why',
      'You Will Never Believe These Bizarre Truth Behind ##KEYWORD##',
      'You Will Never Believe These Bizarre Truth Of ##KEYWORD##',
      'You Will Never Believe These Bizarre Truths Behind ##KEYWORD##',
      'You Will Never Think That Learning ##KEYWORD## Could Be So Beneficial! But It Is',
      'You Will Never Thought That Knowing ##KEYWORD## Could Be So Beneficial',
      'You Will Never Thought That Owning A ##KEYWORD## Could Be So Beneficial',
      'You Will Thank Us - ##COUNT## Tips About ##KEYWORD## You Need To Know',
      'You\'re Welcome. Here Are ##COUNT## Noteworthy Tips About ##KEYWORD##',
      'Your Key To Success: ##KEYWORD##',
      'Your Weakest Link: Use It To ##KEYWORD##',
      '##COUNT## Great ##KEYWORD## Ideas That You Can Share With Your Friends',
      '##COUNT## Reasons Why ##KEYWORD## Is Common In USA',
      'How To Own ##KEYWORD## For Free',
      'The Cheapest Way To Earn Your Free Ticket To ##KEYWORD##'
    ];

    this.prompts = prompts;
  }

  generate_prompts(keyword = 'keyword', num = 10, next) {
    const shuffled = this.prompts.slice(0);
    let i = this.prompts.length;
    const min = i - num;
    let temp = '';
    let index = 0;
    let final_arr: string[];
    while (i-- > min) {
        index = Math.floor((i + 1) * Math.random());
        temp = shuffled[index];
        temp = this._replace_template(temp, keyword);
        shuffled[index] = shuffled[i];
        shuffled[i] = temp;
    }
    final_arr = shuffled.slice(min);
    // console.log('final_arr is of length ' + final_arr.length, final_arr);
    next(null, final_arr);
  }

  private _replace_template(str: string, keyword: string) {
    str = str.replace(/##KEYWORD##/g, keyword);

    // replace year
    const year = new Date().getFullYear().toString();
    str = str.replace(/##YEAR##/g, year);

    // generate a random number between 3 to 10
    const rand = Math.floor(10 * Math.random()) + 3;
    const rand_str = rand.toString();
    str = str.replace(/##COUNT##/g, rand_str);

    // randomly add 'in year' to headlines
    const rand_1 = Math.floor(100 * Math.random()) + 1;
    if ( rand_1 % 7 === 0) {
      str = str + ' in ' + year;
    }

    return str;
  }

}
